/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Conectar.Conectar;
import java.awt.Color;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author TAMY-IA
 */
public class TAMY extends javax.swing.JFrame {
    
    //VARIABLES GLOBALES
    public static String a;
    //////////////////////

    /**
     * Creates new form TAMY
     */
    public TAMY() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        this.setLocationRelativeTo(null);
        jtaTAMY.setLineWrap(true);
        
        ///////////////////
        Reloj rj=new Reloj(jlHora);
        rj.start();
        
        jlFecha.setText(fecha());
        ///////////////////
        
       TAMY();
        
    }
    
    void Ejecutar(){
        String comando=txtDato.getText();
        jtaTAMY.append("-> "+comando+" "+jlHora.getText()+"\n");
        txtDato.setText("");
        //TAMY();
    }
    
    void TAMY(){
        String Hora=jlHora.getText();
        jtaTAMY.append("->1 "+Hora+"\n");
        //txtDato.setText(Hora);
        /*
        if(){
            
        }
        */
        jtaTAMY.setText("Bienvenido mi nombre es TAMY \n");
        
        /////////////////AQUI INICIAN LAS PREGUNTAS/////////////////////////////////
        
        /////////////////AQUI TERMINAN LAS PREGUNTAS/////////////////////////////////
    }
    
    public static String fecha(){
        java.util.Date fecha = new java.util.Date();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
        
        return formatofecha.format(fecha);
    }
    
    void fecha2(){
        Date objDate = new Date(); // Sistema actual La fecha y la hora se asignan a objDate 
 
        System.out.println(objDate); 
        String strDateFormat = "hh: mm: ss a dd-MMM-aaaa"; // El formato de fecha está especificado  
        SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat); // La cadena de formato de fecha se pasa como un argumento al objeto 
        //de formato de fecha  
        System.out.println(objSDF.format(objDate)); // El formato de fecha se aplica a la fecha actual
    }
    //////////Protocolos de seguridad//////////////////////////////////////////
    public static String id;
    
    void ProtocoloNivelAcceso(){
        
    }
    
    ///////////Fin de protocoloes de seguridad///////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFecha = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        jlTAMY = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaTAMY = new javax.swing.JTextArea();
        txtDato = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TAMY Soporte");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlFecha.setForeground(new java.awt.Color(0, 204, 0));
        jlFecha.setText("DD/MM/AAAA");
        getContentPane().add(jlFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, 20));

        jlHora.setForeground(new java.awt.Color(0, 204, 0));
        jlHora.setText("HH:MM:SS");
        getContentPane().add(jlHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 60, 20));

        jlTAMY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMY/Interfaz_1.gif"))); // NOI18N
        getContentPane().add(jlTAMY, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 57, -1, 286));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Instant Messaging Soporte");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 23, -1, -1));

        jtaTAMY.setEditable(false);
        jtaTAMY.setBackground(new java.awt.Color(0, 0, 0));
        jtaTAMY.setColumns(20);
        jtaTAMY.setForeground(new java.awt.Color(0, 51, 204));
        jtaTAMY.setRows(5);
        jScrollPane1.setViewportView(jtaTAMY);

        txtDato.setBackground(new java.awt.Color(0, 0, 0));
        txtDato.setForeground(new java.awt.Color(0, 51, 153));
        txtDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(txtDato)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDato, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 349, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoActionPerformed
        // TODO add your handling code here:
        Ejecutar();
    }//GEN-LAST:event_txtDatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TAMY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlTAMY;
    private javax.swing.JTextArea jtaTAMY;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
    Conectar cc=new Conectar();
    Connection cn=cc.conexion();
}
